CREATE DATABASE IF NOT EXISTS `image_db`;
CREATE DATABASE IF NOT EXISTS `user_db`;
CREATE DATABASE IF NOT EXISTS `busking_db`;
CREATE DATABASE IF NOT EXISTS `inventory_db`;
CREATE DATABASE IF NOT EXISTS `reservation_db`;
CREATE DATABASE IF NOT EXISTS `payment_db`;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';