input {
  tcp {
    port => 5044
    codec => json_lines # 스프링 LogstashEncoder와 매칭
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-logs-%{+YYYY.MM.dd}"
  }
}